### PR TITLE
Docs/ornithopter description

### PR DESCRIPTION
**Pull request by arnau**
**Just for discussion**

@phil-linnell check the syntax section in the README.  It is a first attempt to give names to each concept as well as try to challenge edge cases of our approach (syntax-wise).

### CODE REVIEW

**Comment by phil-linnell** [comment]
It's lovely! :) 

One thing: (and has maybe been a mistake in our examples) but now I've realised the concept parallels with the transition property, perhaps we should have delay at the end? So:

<composed-value>    = [<value>+ || <composed-function>] <duration>? <timing-function>? <delay>?

Having said that I've realised that as these last three attributes are optional (the same as transition) then it matters little!

**Comment by phil-linnell** [comment]
Could this `<property>`: Any valid CSS property, arguably be `<transition-property>`: Any valid CSS property to be animated.  ?

**Comment by phil-linnell** [comment]
I've taken that concept from https://developer.mozilla.org/en-US/docs/Web/CSS/transition

**Comment by arnau** [comment]
Well, although `<duration>`, `<delay>` and `<timing-function>` are optional, the order matters for duration and delay.  The `animation` declaration infers that the first numeric value will be a duration thus you can't have just a delay.

I find this freedom a bit confusing but happy to change to "anyorder".

**Comment by arnau** [comment]
This new commit defines `<timing>` as `[<duration> <delay>?] | <timing-function>]` which means the following are valid:

```
1s                           // 1s of duration
1s 0.5s                   //  1s of duration, 0.5s of delay
ease-out                //  ease-out timing function
1s ease-out           //  1s of duration, ease-out timing function
1s 0.5s ease-out   //  1s of duration, 0.5s of delay, ease-out timing function
ease-out 1s           //  ease-out timing function, 1s of duration
ease-out 1s 0.5s   //  ease-out timing function, 1s of duration, 0.5s of delay
```

I did a tweak on the meaning of `<property>` as you suggested.

**Pull request closed without merging**
